import os
import json
import numpy as np
import torch
import xarray as xr

from model import OceanEmbedModel

def run_predictions():
    print("=" * 80)
    print("STAGE 13 & 14: 15-DEPTH PREDICTION & 3D TEMPERATURE FIELD RECONSTRUCTION")
    print("=" * 80)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")

    model_path = os.path.join("models", "ocean_embed_model.pth")
    data_dir = os.path.join("data", "processed")

    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Model file '{model_path}' not found. Please train the model first.")

    X_norm = np.load(os.path.join(data_dir, "X_norm.npy"))  # Shape: (31, 5, 101, 241)
    ocean_mask = np.load(os.path.join(data_dir, "ocean_mask.npy"))  # Shape: (101, 241)
    grid = np.load(os.path.join(data_dir, "grid.npz"))
    lats = grid['lat']
    lons = grid['lon']
    depths = grid['depth']

    with open(os.path.join(data_dir, "norm_params.json"), "r") as f:
        norm_params = json.load(f)

    target_mean = norm_params['target']['mean']
    target_std = norm_params['target']['std']

    T, C_in, H, W = X_norm.shape
    out_depths = len(depths)

    model = OceanEmbedModel(in_channels=C_in, feature_dim=64, hidden_dim=128, out_depths=out_depths).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    print(f"Loaded trained 15-depth OceanEmbed model from '{model_path}'")
    print(f"Running 3D inference for all {T} daily surface observations...")

    X_tensor = torch.tensor(X_norm, dtype=torch.float32).to(device)
    with torch.no_grad():
        preds_norm = model(X_tensor).cpu().numpy()  # Shape: (31, 15, 101, 241)

    preds_degC = preds_norm * target_std + target_mean

    for t in range(T):
        for d in range(out_depths):
            preds_degC[t, d, ~ocean_mask] = np.nan

    print(f"Predictions generated successfully!")
    print(f"3D Predicted Temperature Range: Min = {np.nanmin(preds_degC):.2f}°C, Max = {np.nanmax(preds_degC):.2f}°C")

    times = [f"2020-01-{day+1:02d}" for day in range(T)]

    ds_pred = xr.Dataset(
        data_vars=dict(
            predicted_temperature=(["time", "depth", "latitude", "longitude"], preds_degC)
        ),
        coords=dict(
            time=times,
            depth=depths,
            latitude=lats,
            longitude=lons
        ),
        attrs=dict(
            description="3D Subsurface Ocean Temperature Predictions generated by OceanEmbed AI Model across 15 Depths",
            units="degrees_C",
            framework="PyTorch + Xarray"
        )
    )

    out_nc_path = os.path.join(data_dir, "predictions_3d.nc")
    
    # Safely remove existing file if present to avoid Windows file locks
    if os.path.exists(out_nc_path):
        try:
            os.remove(out_nc_path)
        except Exception:
            out_nc_path = os.path.join(data_dir, "predictions_3d_v2.nc")

    ds_pred.to_netcdf(out_nc_path)
    ds_pred.close()
    
    # Also save as npy for fast zero-lock loading by Streamlit
    np.save(os.path.join(data_dir, "preds_3d.npy"), preds_degC)
    
    print(f"Saved 3D daily 15-depth temperature field predictions to '{out_nc_path}'!")

if __name__ == "__main__":
    run_predictions()
